/*

 File: C:\gm_tutorial1_1_ref_build\gm_tutorial1_1_ref_dpi.h
 Created: 2021-02-02 16:16:36
 Generated by MATLAB 9.9 and HDL Verifier 6.2

*/

#ifndef RTW_HEADER_gm_tutorial1_1_ref_dpi_h_
#define RTW_HEADER_gm_tutorial1_1_ref_dpi_h_

#ifdef __cplusplus
#define DPI_LINK_DECL extern "C"
#else
#define DPI_LINK_DECL
#endif

#ifndef DPI_DLL_EXPORT
#if defined(_MSC_VER) || defined(__LCC__)
#define DPI_DLL_EXPORT __declspec(dllexport)
#else
#define DPI_DLL_EXPORT 
#endif
#endif






DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_gm_tutorial1_1_ref_initialize(void* existhandle);
DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_gm_tutorial1_1_ref_reset(void* objhandle, int16_T* dpi_1_re, int16_T* dpi_1_im, int16_T* dpi_2_re, int16_T* dpi_2_im, int32_T* dpi_3_re, int32_T* dpi_3_im);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_gm_tutorial1_1_ref_output(void* objhandle, int16_T* dpi_1_re, int16_T* dpi_1_im, int16_T* dpi_2_re, int16_T* dpi_2_im, int32_T* dpi_3_re, int32_T* dpi_3_im);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_gm_tutorial1_1_ref_update(void* objhandle);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_gm_tutorial1_1_ref_terminate(void* objhandle);

#endif /*RTW_HEADER_gm_tutorial1_1_ref_dpi_h_*/

