/*

 File: C:\gm_tutorial1_1_ref_build\gm_tutorial1_1_ref_dpi.c
 Created: 2021-02-02 16:16:36
 Generated by MATLAB 9.9 and HDL Verifier 6.2

*/

#include "gm_tutorial1_1_ref.h"
#include "gm_tutorial1_1_ref_dpi.h"

#ifndef RT_MEMORY_ALLOCATION_ERROR_DEF
#define RT_MEMORY_ALLOCATION_ERROR_DEF
const char *RT_MEMORY_ALLOCATION_ERROR = "memory allocation error";
#endif
static RT_MODEL_gm_tutorial1_1_ref_T* RT_MODEL_gm_tutorial1_1_ref = NULL;







DPI_DLL_EXPORT void* DPI_gm_tutorial1_1_ref_initialize(void* existhandle)
{
RT_MODEL_gm_tutorial1_1_ref_T* objhandle;

if(existhandle==NULL)
{
	objhandle=gm_tutorial1_1_ref();
}else{
	objhandle=(RT_MODEL_gm_tutorial1_1_ref_T*)existhandle;
}
gm_tutorial1_1_ref_initialize(objhandle);


return (void*)objhandle;
}

DPI_DLL_EXPORT void* DPI_gm_tutorial1_1_ref_reset(void* objhandle, int16_T* dpi_1_re, int16_T* dpi_1_im, int16_T* dpi_2_re, int16_T* dpi_2_im, int32_T* dpi_3_re, int32_T* dpi_3_im)
{
    DPI_gm_tutorial1_1_ref_terminate(objhandle);
    objhandle=NULL;
    objhandle=DPI_gm_tutorial1_1_ref_initialize(NULL);
    DPI_gm_tutorial1_1_ref_output(objhandle,dpi_1_re,dpi_1_im,dpi_2_re,dpi_2_im,dpi_3_re,dpi_3_im);
    DPI_gm_tutorial1_1_ref_terminate(objhandle);
    objhandle=NULL;
    return DPI_gm_tutorial1_1_ref_initialize(NULL);
    
}

DPI_DLL_EXPORT void DPI_gm_tutorial1_1_ref_output(void* objhandle, int16_T* dpi_1_re, int16_T* dpi_1_im, int16_T* dpi_2_re, int16_T* dpi_2_im, int32_T* dpi_3_re, int32_T* dpi_3_im)
{
    
    
    
    
    
    cint16_T* _dpi_1_Ptr = &((RT_MODEL_gm_tutorial1_1_ref_T*) objhandle )->outputs->dpi_1;
    cint16_T* _dpi_2_Ptr = &((RT_MODEL_gm_tutorial1_1_ref_T*) objhandle )->outputs->dpi_2;
    cint32_T* _dpi_3_Ptr = &((RT_MODEL_gm_tutorial1_1_ref_T*) objhandle )->outputs->dpi_3;
    
    
    
    
    gm_tutorial1_1_ref_output(((RT_MODEL_gm_tutorial1_1_ref_T*) objhandle ));
    
    *dpi_1_re=(*_dpi_1_Ptr).re;
    
    
    
    *dpi_1_im=(*_dpi_1_Ptr).im;
    
    
    
    *dpi_2_re=(*_dpi_2_Ptr).re;
    
    
    
    *dpi_2_im=(*_dpi_2_Ptr).im;
    
    
    
    *dpi_3_re=(*_dpi_3_Ptr).re;
    
    
    
    *dpi_3_im=(*_dpi_3_Ptr).im;
    
    
    
    
    
}

DPI_DLL_EXPORT void DPI_gm_tutorial1_1_ref_update(void* objhandle)
{
    
    
    
    
    
    
    
    gm_tutorial1_1_ref_update(((RT_MODEL_gm_tutorial1_1_ref_T*) objhandle ));
}

DPI_DLL_EXPORT void DPI_gm_tutorial1_1_ref_terminate(void* objhandle)
{
    gm_tutorial1_1_ref_terminate(((RT_MODEL_gm_tutorial1_1_ref_T*)objhandle));
}


