open_system('gm_homework1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_homework1/HDL_Complex_Multiplier/Delay2', 'user1');
annotate_port('gm_homework1/HDL_Complex_Multiplier/Delay2', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_homework1/HDL_Complex_Multiplier/Delay3', 'user1');
annotate_port('gm_homework1/HDL_Complex_Multiplier/Delay3', 1, 1, 'cp : 3.777 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_homework1/HDL_Complex_Multiplier/Bit Slice1', 'user2');
annotate_port('gm_homework1/HDL_Complex_Multiplier/Bit Slice1', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_homework1/HDL_Complex_Multiplier/Bitwise Operator1', 'user2');
annotate_port('gm_homework1/HDL_Complex_Multiplier/Bitwise Operator1', 0, 1, 'cp : 2.459 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_homework1/HDL_Complex_Multiplier/Multiport Switch', 'user2');
annotate_port('gm_homework1/HDL_Complex_Multiplier/Multiport Switch', 0, 1, 'cp : 1.993 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_homework1/HDL_Complex_Multiplier/Multiport Switch1', 'user2');
annotate_port('gm_homework1/HDL_Complex_Multiplier/Multiport Switch1', 0, 1, 'cp : 3.747 ns');
