open_system('gm_tutorial1_1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_tutorial1_1/HDL_Complex_Multiplier/Delay', 'user1');
annotate_port('gm_tutorial1_1/HDL_Complex_Multiplier/Delay', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_tutorial1_1/HDL_Complex_Multiplier/Delay3', 'user1');
annotate_port('gm_tutorial1_1/HDL_Complex_Multiplier/Delay3', 1, 1, 'cp : 5.463 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_tutorial1_1/HDL_Complex_Multiplier/Complex to Real-Imag', 'user2');
annotate_port('gm_tutorial1_1/HDL_Complex_Multiplier/Complex to Real-Imag', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_tutorial1_1/HDL_Complex_Multiplier/Product2', 'user2');
annotate_port('gm_tutorial1_1/HDL_Complex_Multiplier/Product2', 0, 1, 'cp : 5.463 ns');
