/*

 File: C:\gm_homework1_ref_build\gm_homework1_ref_dpi.c
 Created: 2021-02-20 12:46:54
 Generated by MATLAB 9.9 and HDL Verifier 6.2

*/

#include "gm_homework1_ref.h"
#include "gm_homework1_ref_dpi.h"

#ifndef RT_MEMORY_ALLOCATION_ERROR_DEF
#define RT_MEMORY_ALLOCATION_ERROR_DEF
const char *RT_MEMORY_ALLOCATION_ERROR = "memory allocation error";
#endif
static RT_MODEL_gm_homework1_ref_T* RT_MODEL_gm_homework1_ref = NULL;







DPI_DLL_EXPORT void* DPI_gm_homework1_ref_initialize(void* existhandle)
{
RT_MODEL_gm_homework1_ref_T* objhandle;

if(existhandle==NULL)
{
	objhandle=gm_homework1_ref();
}else{
	objhandle=(RT_MODEL_gm_homework1_ref_T*)existhandle;
}
gm_homework1_ref_initialize(objhandle);


return (void*)objhandle;
}

DPI_DLL_EXPORT void* DPI_gm_homework1_ref_reset(void* objhandle, int64_T* dpi_1, int64_T* dpi_2, uint8_T* dpi_3, int64_T* dpi_4)
{
    DPI_gm_homework1_ref_terminate(objhandle);
    objhandle=NULL;
    objhandle=DPI_gm_homework1_ref_initialize(NULL);
    DPI_gm_homework1_ref_output(objhandle,dpi_1,dpi_2,dpi_3,dpi_4);
    DPI_gm_homework1_ref_terminate(objhandle);
    objhandle=NULL;
    return DPI_gm_homework1_ref_initialize(NULL);
    
}

DPI_DLL_EXPORT void DPI_gm_homework1_ref_output(void* objhandle, int64_T* dpi_1, int64_T* dpi_2, uint8_T* dpi_3, int64_T* dpi_4)
{
    
    
    
    
    int64_T* dpi_1_Ptr = dpi_1;
    int64_T* dpi_2_Ptr = dpi_2;
    uint8_T* dpi_3_Ptr = dpi_3;
    int64_T* dpi_4_Ptr = dpi_4;
    
    int64_T* RT_MODEL_gm_homework1_ref_output_dpi_1_Ptr = &(((RT_MODEL_gm_homework1_ref_T*) objhandle )->outputs->dpi_1);
    int64_T* RT_MODEL_gm_homework1_ref_output_dpi_2_Ptr = &(((RT_MODEL_gm_homework1_ref_T*) objhandle )->outputs->dpi_2);
    uint8_T* RT_MODEL_gm_homework1_ref_output_dpi_3_Ptr = &(((RT_MODEL_gm_homework1_ref_T*) objhandle )->outputs->dpi_3);
    int64_T* RT_MODEL_gm_homework1_ref_output_dpi_4_Ptr = &(((RT_MODEL_gm_homework1_ref_T*) objhandle )->outputs->dpi_4);
    
    
    
    
    gm_homework1_ref_output(((RT_MODEL_gm_homework1_ref_T*) objhandle ));
    
    
    *dpi_1_Ptr=*RT_MODEL_gm_homework1_ref_output_dpi_1_Ptr;
    *dpi_2_Ptr=*RT_MODEL_gm_homework1_ref_output_dpi_2_Ptr;
    *dpi_3_Ptr=*RT_MODEL_gm_homework1_ref_output_dpi_3_Ptr;
    *dpi_4_Ptr=*RT_MODEL_gm_homework1_ref_output_dpi_4_Ptr;
    
}

DPI_DLL_EXPORT void DPI_gm_homework1_ref_update(void* objhandle)
{
    
    
    
    
    
    
    
    gm_homework1_ref_update(((RT_MODEL_gm_homework1_ref_T*) objhandle ));
}

DPI_DLL_EXPORT void DPI_gm_homework1_ref_terminate(void* objhandle)
{
    gm_homework1_ref_terminate(((RT_MODEL_gm_homework1_ref_T*)objhandle));
}


