/*

 File: C:\gm_homework1_ref_build\gm_homework1_ref_dpi.h
 Created: 2021-02-20 12:46:54
 Generated by MATLAB 9.9 and HDL Verifier 6.2

*/

#ifndef RTW_HEADER_gm_homework1_ref_dpi_h_
#define RTW_HEADER_gm_homework1_ref_dpi_h_

#ifdef __cplusplus
#define DPI_LINK_DECL extern "C"
#else
#define DPI_LINK_DECL
#endif

#ifndef DPI_DLL_EXPORT
#if defined(_MSC_VER) || defined(__LCC__)
#define DPI_DLL_EXPORT __declspec(dllexport)
#else
#define DPI_DLL_EXPORT 
#endif
#endif






DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_gm_homework1_ref_initialize(void* existhandle);
DPI_LINK_DECL DPI_DLL_EXPORT void* DPI_gm_homework1_ref_reset(void* objhandle, int64_T* dpi_1, int64_T* dpi_2, uint8_T* dpi_3, int64_T* dpi_4);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_gm_homework1_ref_output(void* objhandle, int64_T* dpi_1, int64_T* dpi_2, uint8_T* dpi_3, int64_T* dpi_4);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_gm_homework1_ref_update(void* objhandle);
DPI_LINK_DECL DPI_DLL_EXPORT void DPI_gm_homework1_ref_terminate(void* objhandle);

#endif /*RTW_HEADER_gm_homework1_ref_dpi_h_*/

