open_system('gm_tutorial1_1');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_tutorial1_1/HDL_Complex_Multiplier/Product', 'user2');
annotate_port('gm_tutorial1_1/HDL_Complex_Multiplier/Product', 0, 1, 'cp : 5.463 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_tutorial1_1/HDL_Complex_Multiplier/PipelineRegister', 'user1');
annotate_port('gm_tutorial1_1/HDL_Complex_Multiplier/PipelineRegister', 1, 1, 'cp : 5.463 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_tutorial1_1/HDL_Complex_Multiplier/HwModeRegister', 'user1');
annotate_port('gm_tutorial1_1/HDL_Complex_Multiplier/HwModeRegister', 0, 1, 'cp : 0.298 ns');
